src/jumpserver/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from jumpserver.views import index


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', index, name='index'),
    url(r'juser/', include('juser.urls', namespace='juser')),

]

src/juser/urls.py
from django.conf.urls import url
from .views import (
    group_list,
    group_add,
    group_edit,
    group_del,
    user_edit,
    user_list,
    user_add,
    user_del,
    down_key,
    regen_ssh_key,
)

urlpatterns = [

    url(r'group/list/$', group_list, name='user_group_list'),
    url(r'group/add/$', group_add, name='user_group_add'),
    url(r'group/edit/$', group_edit, name='user_group_edit'),
    url(r'group/del/$', group_del, name='user_group_del'),
    url(r'user/list/$', user_list, name='user_list'),
    url(r'user/edit/$', user_edit, name='user_edit'),
    url(r'user/del/$', user_del, name='user_del'),
    url(r'user/add/$', user_add, name='user_add'),
    url(r'key/gen/$', regen_ssh_key, name='key_gen'),
    url(r'key/down/$', down_key, name='key_down'),

]

src/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Jumpserver | 开源跳板机</title>

    <link rel="shortcut icon" href="{% static 'img/facio.ico' %}" type="image/x-icon">
    {% include 'link_css.html' %}
    {% include 'head_script.html' %}
    {% block sel_head_css_js %}{% endblock %}
</head>
<body>

   <div id= "wrapper">
        {% include 'nav.html' %}
        <div id="page-wrapper" class="gray-bg">
            <div class="row border-bottom">
                {% include 'nav_bar_header.html' %}
            </div>
            {% block content %}{% endblock %}
            {% include 'footer.html' %}
        </div>

    </div>
</body>
    {% include 'footer_script.html' %}
    {% block self_footer_js %}{% endblock %}
</html>

src/templates/footer.html
<div class="footer fixed">
    <div class="pull-right">
        Version <strong>0.3.2</strong> GPL.
    </div>
    <div>
        <strong>Copyright</strong>Jumpserver.org Team &copy;2015-2016
    </div>
</div>

src/templates/footer_script.html
{% load staticfiles %}
<!-- Mainly scripts -->
<script src="{% static 'js/plugins/metisMenu/jquery.metisMenu.js' %}"></script>
<script src="{% static 'js/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>
<script src="{% static 'js/bootstrap-dialog.js' %}"></script>
<script src="{% static 'js/mindmup-editabletable.js' %}"></script>
<script src="{% static 'js/plugins/fullcalendar/moment.min.js' %}"></script>
<script src="{% static 'js/plugins/fullcalendar/fullcalendar.min.js' %}"></script>

<!-- Custom and plugin javascript -->
<script src="{% static 'js/inspinia.js' %}"></script>
<script src="{% static 'js/plugins/pace/pace.min.js' %}"></script>

<!-- Peity -->
<script src="{% static 'js/plugins/peity/jquery.peity.min.js' %}"></script>

<!-- Peity -->
<script src="{% static 'js/demo/peity-demo.js' %}"></script>

<script src="{% static 'js/base.js' %}"></script>

<!-- pop windows layer-->
<script src="{% static 'js/layer/layer.js' %}"></script>

<!-- highcharts -->
<script src="{% static 'js/highcharts/highcharts.js' %}"></script>


<script src="{% static 'js/dropzone/dropzone.js' %}"></script>
<!-- active menu -->
<script>
    var url_array = document.location.pathname.split("/");
    s1 = url_array[1];
    s2 = url_array[2];
    if (s1 == ''){
        $('#index').addClass('active')
    } else {
        $("#"+s1).addClass('active');
        $('#'+s1+' .'+s2).addClass('active');
    }
</script>

src/templates/head_script.html
{% load staticfiles %}
<script src="{% static 'js/jquery-2.1.1.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/base.js' %}"></script>

<!--POP Windows -->
<script src="{% static 'js/jquery.colorbox.js' %}"></script>

<!-- validator js -->
<script src="{% static 'js/validator/jquery.validator.js' %}"></script>
<script src="{% static 'js/validator/zh_CN.js' %}"></script>

<script src="{% static 'js/datapicker/bootstrap-datepicker.js' %}"></script>

src/templates/link_css.html
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.css' %}">
<link rel="stylesheet" href="{% static 'css/plugins/iCheck/custom.css' %}">
<link rel="stylesheet" href="{% static 'css/animate.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/colorbox.css' %}">
<link rel="stylesheet" href="{% static 'css/vaildator/jquery.validator.css' %}">
<link rel="stylesheet" href="{% static 'css/magnific/magnific-popup.css' %}">
<link rel="stylesheet" href="{% static 'css/plugins/fullcalendar/fullcalendar.css' %}">
<link rel="stylesheet" href="{% static 'css/plugins/dropzone/dropzone.css' %}">
<link rel="stylesheet" href="{% static 'css/plugins/dropzone/basic.css' %}">

src/templates/nav.html
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav" id="side-menu">
            {% include "nav_li_profile.html" %}
            <li id="index">
                <a href="#"><i class="fa fa-dashboard"></i><span class="nav-label">仪表盘</span><span class="label label-info pull-right"></span></a>
            </li>
            <li id="juser">
                <a href="#"><i class="fa fa-group"></i><span class="nav-label">用户管理</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li class="group">
                        <a href="{% url 'juser:user_group_list' %}">查看用户组</a>
                    </li>
                    <li class="group">
                        <a href="{% url 'juser:user_list' %}">查看用户<span class="label label-primary" >5/5</span></a>
                    </li>
                </ul>
            </li>

            <li id="jasset">
                <a href="#"><i class="fa fa-inbox"></i><span class="nav-label">资产管理</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li class="group">
                        <a href="#">查看资产组</a>
                    </li>
                    <li class="asset">
                        <a href="#">查看资产<span class="label label-info pull-right">5/5</span></a>
                    </li>
                    <li class="idc">
                        <a href="#">查看机房</a>
                    </li>
                </ul>
            </li>

            <li id="jperm">
                <a href="#"><i class="fa fa-edit"></i><span class="nav-label">授权管理</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li class="sudo">
                        <a class="sudo" href="#">Sudo</a>
                    </li>
                    <li class="role">
                        <a href="#">系统用户</a>
                    </li>
                    <li class="rule">
                        <a href="#">授权规则</a>
                    </li>
                </ul>
            </li>

            <li id="jlog">
                <a href="#"><i class="fa fa-gears"></i><span class="nav-label">设置</span><span class="label label-info pull-right"></span></a>
            </li>

            <li id="special_link">
                <a href="#"><i class="fa fa-database"></i><span class="nav-label">访问官网</span></a>
            </li>
        </ul>
    </div>

</nav>

src/templates/nav_bar_header.html
<nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <a class="navbar-minimalize minimalize-styl-2 btn btn-primary" href="#"><i class="fa fa-bars"></i></a>
        <form role="search" class="navbar-form-custom" method="GET" action="">
            <div class="form-group">
                <input type="text" placeholder="输入搜索..." class="form-control" id="top-search" name="search">
            </div>
        </form>
    </div>

    <ul class="nav navbar-top-links navbar-right">
        <li>
            <span class="m-r-sm text-muted welcome-message">欢迎使用开源跳板机</span>
        </li>
        <li class="dropdown">
            <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                <span class="m-r-sm text-muted welcome-message">帮助</span>
            </a>
        </li>
        <li>
            <a href="#">
                <i class="fa fa-sign-out"></i>Log out
            </a>
        </li>
    </ul>

</nav>

src/templates/nav_cat_bar.html
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-10">
        <h2>{{ header_title }}</h2>
        <ol class="breadcrumb">
            <li>
                <a href="#">仪表盘</a>
            </li>
            <li>
                {% if path1 %}
                    <a>{{ path1 }}</a>
                {% endif %}
            </li>
            {% if path2 %}
                <li>
                    <strong>{{ path2 }}</strong>
                </li>
            {% endif %}
        </ol>
    </div>
    <div class="col-sm-2">
    </div>
</div>

src/templates/nav_li_profile.html
<li class="nav-header">

    <div class="dropdown profile-element">

        <span>
            <img  class="img-circle" width="48" height="48"  src="">
        </span>

        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
            <span class="clear">
                <span class="block m-t-xs">
                    <strong class="font-bold">admin<span style="color: #8095a8"></span></strong>
                </span>
                <span class="text-muted text-xs block">
                    超级管理员<b class="caret"></b>
                </span>
            </span>

        </a>
        <ul class="dropdown-menu animated fadeInRight m-t-xs">
            <li><a class="iframe_user">个人信息</a></li>
            <li><a>修改信息</a></li>
            <li class="divider"></li>
            <li><a>注销</a></li>
        </ul>
    </div>

    <div class="logo-element">
        JS+
    </div>

</li>

<script>
    $(".iframe_user").on('click',function(){
        var url = $(this).attr("value")
        layer.open({
            type:2,
            title:"个人信息",
            maxmin:true,
            shift:"top",
            border:[2,0.3,"#1AB394"],
            shade:[0.5,"#000000"],
            shadeClose:true,
            area:["800px","600px"],
            content:url
        })
    })
</script>

src/templates/paginator.html
<div class="col-sm-6">
    <div class="dataTables_paginate paging-simple-numbers" id="editable-paginate">
        <ul class="pagination" style="margin-top: 0;float: right">
            {% if contacts.has_previous %}
                <li class="paginate_button previous" aria-controls="editable" tabindex="0" id="editable-previous">
                    <a class="page" href="?page={{ contacts.previous_page_number }}">Previous</a>
                </li>
            {% else %}
                 <li class="paginate_button previous disabled" aria-controls="editable" tabindex="0" id="editable_previous">
                    <a class="page" href="#">Previous</a>
                </li>
            {% endif %}
            {% ifequal show_first 1 %}
                <li class="paginate_button" aria-controls="editable" tabindex="0"><a class="page" href="?page=1" title="第一页">1...</a></li>
            {% endifequal %}
            {% for page in page_range %}
                {% ifequal page current_page  %}
                    <li class="paginate_button active" aria-controls="editable" tabindex="0"><a class="page" href="?page={{ page }}" title="第{{ page }}页">{{ page }}</a></li>
                {% else %}
                    <li class="paginate_button" aria-controls="editable" tabindex="0"><a class="page" href="?page={{ page }}" title="第{{ page }}页">{{ page }}</a></li>
                {% endifequal %}
            {% endfor %}
            {% ifequal show_end 1  %}
                <li class="paginate_button" aria-controls="editable" tabindex="0"><a class="page" href="?page={{ p.num_pages }}" title="第{{ page }}页">{{ p.num_pages }}</a></li>
            {% endifequal %}
             {% if contacts.has_next %}
                <li class="paginate_button next" aria-controls="editable" tabindex="0" id="editable-previous">
                    <a class="page" href="?page={{ contacts.next_page_number }}">Next</a>
                </li>
            {% else %}
                 <li class="paginate_button previous disabled" aria-controls="editable" tabindex="0" id="editable_next">
                    <a class="page" href="#">Next</a>
                </li>
            {% endif %}
        </ul>
    </div>
</div>

<script>

</script>