src/jumpserver/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from jumpserver.views import index


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', index, name='index'),
    url(r'juser/', include('juser.urls', namespace='juser')),

]

src/juser/urls.py
from django.conf.urls import url
from .views import (
    group_list,
    group_add,
    group_edit,
    group_del,
    user_edit,
    user_list,
    user_add,
    user_del,
    down_key,
    regen_ssh_key,
)

urlpatterns = [

    url(r'group/list/$', group_list, name='user_group_list'),
    url(r'group/add/$', group_add, name='user_group_add'),
    url(r'group/edit/$', group_edit, name='user_group_edit'),
    url(r'group/del/$', group_del, name='user_group_del'),
    url(r'user/list/$', user_list, name='user_list'),
    url(r'user/edit/$', user_edit, name='user_edit'),
    url(r'user/del/$', user_del, name='user_del'),
    url(r'user/add/$', user_add, name='user_add'),
    url(r'key/gen/$', regen_ssh_key, name='key_gen'),
    url(r'key/down/$', down_key, name='key_down'),

]

src/juser/models.py
#_*_coding:utf8_*
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import (
    BaseUserManager,
    AbstractBaseUser)
import time
# Create your models here.

class UserGroup(models.Model):
    name = models.CharField(max_length=80, unique=True)
    comment = models.CharField(max_length=160,blank=True,null=True)

    def __unicode__(self):
        return self.name

class UserManager(BaseUserManager):
    def create_user(self, email, name, password=None):
        if not email:
            raise ValueError('User mut have an email address')
        user = self.model(email=self.normalize_email(email), name=name)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, name, password):
        user = self.create_user(email=email, name=name, password=password)
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    email = models.EmailField(verbose_name='email address', max_length=255, unique=True)
    username = models.CharField(max_length=80, blank=True, null=True, default='')
    name = models.CharField(max_length=80)
    uuid = models.CharField(max_length=100)
    USER_ROLE_CHOICE = (
        ('SU', 'SuperUser'),
        ('GA', 'GroupAdmin'),
        ('CU', 'CommonUser'),
    )
    role = models.CharField(max_length=2, choices=USER_ROLE_CHOICE, default='CU')
    group = models.ManyToManyField(UserGroup)
    ssh_key_pwd = models.CharField(max_length=200)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    date_joined = models.DateTimeField(auto_now=True)
    objects = UserManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name', 'password', ]

    def get_full_name(self):
        return self.name

    def get_short_name(self):
        return self.name

    def __unicode__(self):
        return self.email

    def has_perm(self, perm, object=None):
        return True

    def has_module_perms(self,app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin


class AdminGroup(models.Model):
    user = models.ForeignKey(User)
    group = models.ForeignKey(UserGroup)

    def __unicode__(self):
        return "%s: %s"(self.user.name, self.group.name)


def upload_to(instance,filename):
        return 'upload/' + str(instance.user.id) + time.strftime("/%Y/%m/%d", time.localtime()) + filename
class Document(models.Model):
    user = models.ForeignKey(User)
    docfile = models.FileField(upload_to=upload_to)

src/juser/views.py
# coding: utf-8
from django.shortcuts import (
    render,
    render_to_response,
    get_object_or_404
)
from django.http import (
    HttpResponseRedirect,
    HttpResponse,
)
from django.core.urlresolvers import reverse
from django.db.models import Q
from .models import UserGroup
import datetime
import uuid
from jumpserver.api import pages
from .models import User
from jumpserver.api import (
    ServerError,
    PyCrypt,
    is_role_request,
)
from .user_api import (
    db_add_group,
    db_add_user,
    db_update_user,
    get_object,
    server_add_user,
    db_del_user,
    server_del_user,
    user_add_mail,
    get_display_msg,
    gen_ssh_key,
    logger,
)
from django.conf import settings
from django.core.mail import send_mail
import os
# Create your views here.


def group_add(request):
    """
    添加用户组
    :param request:
    :return:
    """
    header_title, path1, path2 = u'添加用户组', u'用户管理', u'添加用户组'
    error = ""
    msg = ""
    user_all = User.objects.all()

    if request.method == 'POST':
        group_name = request.POST.get('group_name', '')
        users_selected = request.POST.getlist('users_selected','')
        comment = request.POST.get('comment','')

        try:
            if not group_name:
                error = u'组名不能为空'
                raise ServerError(error)
            if UserGroup.objects.filter(name=group_name):
                error = u'组名已存在'
                raise ServerError(error)
            db_add_group(name=group_name, users_id=users_selected, comment=comment)
        except ServerError:
            pass
        except TypeError:
            error = u'添加组失败'
        else:
            msg = u'添加组 %s 成功' % group_name

    return render(request, 'juser/group_add.html', locals())


def group_list(request):
    header_title, path1, path2 = u'查看用户组', u'用户管理', u'查看用户组'
    keyword = request.GET.get('search', '')
    user_group_list = UserGroup.objects.all().order_by('name')
    group_id = request.GET.get('id','')

    if keyword:
        user_group_list = user_group_list.filter(Q(name__icontains=keyword) | Q(comment__icontains=keyword))

    if group_id:
        user_group_list = user_group_list.filter(id=int(group_id))

    user_group_list, p, user_groups, page_range, current_page, show_first, show_end = pages(user_group_list, request)

    return render(request, 'juser/group_list.html', context=locals())


def group_del(request):
    """
    删除用户组
    :param request:
    :return:
    """
    group_ids = request.GET.get('id')
    group_id_list = group_ids.split(',')
    for group_id in group_id_list:
        UserGroup.objects.filter(id=group_id).delete()

    return HttpResponse('删除成功')


def group_edit(request):
    header_title, path1, path2 = u'编辑用户组', u'用户管理', u'编辑用户组'
    error = ''
    msg = ''

    print 'Begin request'
    if request.method == 'GET':
        group_id = request.GET.get('id', '')
        user_group = get_object(UserGroup, id=group_id)
        print user_group
        users_selected = User.objects.filter(group=user_group)
        users_remain = User.objects.filter(~Q(group=user_group))
        users_all = User.objects.all()

    elif request.method == 'POST':
        group_id = request.POST.get('id', '')
        group_name = request.POST.get('group_name', '')
        users_selected = request.POST.getlist('users_selected', '')
        comment = request.POST.get('comment', '')

        try:
            if '' in [group_name, group_id]:
                error = u'组名不能为空'
                raise ServerError(error)
            if UserGroup.objects.filter(name=group_name).count() > 1:
                error = u'组名已存在'
                raise ServerError(error)
            db_add_group(name=group_name, users_id=users_selected, comment=comment)
            user_group = get_object_or_404(UserGroup, id=group_id)
            user_group.user_set.clear()
            for user in User.objects.filter(id__in=users_selected):
                user.group.add(UserGroup.objects.get(id=group_id))
            user_group.name = group_name
            user_group.comment = comment
            user_group.save()
        except ServerError, e:
            error = e

        if not error:
            return HttpResponseRedirect(reverse('juser:group_list'))
        else:
            users_all = User.objects.all()
            users_selected = User.objects.filter(group=user_group)
            users_remain = User.objects.filter(~Q(group=user_group))

    return render(request, 'juser/group_edit.html', context=locals())


def user_del(request):
    if request.method == 'GET':
        user_ids = request.GET.get('id', '')
        user_id_list = user_ids.split(',')
    elif request.method == 'POST':
        user_ids = request.POST.get('id', '')
        user_id_list = user_ids.split(',')
    else:
        return HttpResponse(u'错误请求')
    print request.POST.get('id')
    for user_id in user_id_list:
        user = get_object(User, id=user_id)
        if user and user.username != 'admin':
            logger.debug(u'删除用户 %s' % user.username)
            server_del_user(user.username)
            user.delete()
    return HttpResponse(u'删除成功',)


def user_add(request):
    header_title, path1, path2 = u'添加用户', u'用户管理', u'添加用户'
    error = ""
    msg = ""
    user_role = {'SU': u'超级管理员', 'CU': u'普通用户'}
    group_all = UserGroup.objects.all()

    if request.method == 'POST':
        username = request.POST.get('username', '')
        password = PyCrypt.gen_rand_pass(16)
        name = request.POST.get('name', '')
        email = request.POST.get('email', '')
        groups = request.POST.getlist('groups', [])
        admin_groups = request.POST.getlist('admin_groups', [])
        role = request.POST.get('role', 'CU')
        uuid_r = uuid.uuid4().get_hex()
        ssh_key_pwd = PyCrypt.gen_rand_pass(16)
        extra = request.POST.get('extra', '')
        is_active = False if '0' in extra else True
        send_mail_need = True if '1' in extra else False

        try:
            if '' in [username, password, ssh_key_pwd, name, role]:
                error= u'带*内容不能为空'
                raise ServerError
            check_user_is_exists = User.objects.filter(username=username)
            if check_user_is_exists:
                error = u'用户 %s 已存在' % username
                raise ServerError
        except ServerError:
            pass

        else:
            try:
                user = db_add_user(username=username, name=name, password=password,
                                   email=email,role=role,uuid=uuid_r,
                                   groups=groups,admin_groups=admin_groups,
                                   ssh_key_pwd=ssh_key_pwd, is_active=is_active,
                                   date_joined=datetime.datetime.now())

                server_add_user(username=username, ssh_key_pwd=ssh_key_pwd)
                user = get_object(User, username=username)
                if groups:
                    user_groups = []
                    for user_group_id in groups:
                        user_groups.extend(UserGroup.objects.filter(id=user_group_id))
            except IndexError, e:
                error = u'添加用户 %s 失败 %s' %(username, e)
                try:
                    db_del_user(username)
                    server_del_user(username)
                except Exception:
                    pass
            else:
                if settings.MAIL_ENABLE and send_mail_need:
                        user_add_mail(user, kwargs=locals())
                msg = get_display_msg(user, password=password, ssh_key_pwd=ssh_key_pwd, send_mail_need=send_mail_need)

    return render(request, 'juser/user_add.html', context=locals())


def user_list(request):
    header_title, path1, path2 = u'查看用户', u'用户管理', u'编辑用户组'
    user_role = {'SU': u'超级管理员', 'GA': u'组管理员', 'CU': u'普通用户'}
    keyword = request.GET.get('keyword', '')
    gid = request.GET.get('gid', '')
    users_list = User.objects.all().order_by('name')

    if gid:
        user_group = UserGroup.objects.filter(id=gid)
        if user_group:
            user_group = user_group.first()
            users_list = user_group.user_set.all()

    if keyword:
        users_list = users_list.filter(Q(name__icontains=keyword)).order_by('name')

    users_list, p, users, page_range, current_page, show_first, show_end = pages(users_list, request)

    return render(request, 'juser/user_list.html', context=locals())


def user_edit(request):
    header_title, path1, path2 = u'编辑用户', u'用户管理', u'编辑用户组'

    if request.method == 'GET':
        user_id = request.GET.get('id', '')
        if not user_id:
            HttpResponseRedirect(reverse('index'))

        user_role = {'SU': u'超级管理员', 'CU': u'普通用户'}
        user = get_object(User, id=user_id)
        group_all = UserGroup.objects.all()
        if user:
            groups_str = ' '.join([str(group.id) for group in user.group.all()])
            admin_groups_str = ' '.join([str(admin_group.group.id) for admin_group in user.admingroup_set.all()])
    else:
        user_id = request.GET.get('id', '')
        password = request.POST.get('password', '')
        name = request.POST.get('name', '')
        email = request.POST.get('email', '')
        role_post = request.POST.get('role', '')
        groups = request.POST.getlist('groups', '')
        admin_groups = request.POST.getlist('admin_groups', [])
        extra = request.POST.getlist('extra', [])
        is_active = True if '0' in extra else False
        email_need = True if '1' in extra else False
        user_role = {'SU': u'超级管理员', 'GA': u'组管理员', 'CU': u'普通用户'}

        if user_id:
            user = get_object(User, id=user_id)
        else:

src/templates/juser/group_list.html
{% extends 'base.html' %}
{% load mytags %}
{% block content %}
{% include 'nav_cat_bar.html' %}

    <div class="wrapper wrapper-content animated fadeinright">
        <div class="row">
            <div class="col-sm-10">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>查看用户组</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>

                    <div class="ibox-content">
                        <div class="">
                            <a href="{% url 'juser:user_group_add' %}" class="btn btn-primary btn-sm">添加用户组</a>
                            <a id="del_btn" class="btn btn-sm btn-danger">删除所选</a>
                            <form id="search_form" method="get" action="" class="pull-right mail-search">
                                <div class="input-group">
                                    <input type="text" class="form-control input-sm" name="search" placeholder="Search" />
                                    <div class="input-group-btn">
                                        <button id="search_btn" type="submit" class="btn btn-sm btn-primary">
                                            -搜索-
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>

                        <table class="table table-striped table-bordered table-hover" id="editable" >
                            <thead>
                                <tr>
                                    <th class="text-center">
                                        <input type="checkbox" id="select_all" name="select_all"/>
                                    </th>
                                    <th class="text-center">组名</th>
                                    <th class="text-center">成员数量</th>
                                    <th class="text-center">备注</th>
                                    <th class="text-center">操作</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for group in user_groups  %}
                                    <tr class="gradeX">
                                        <td class="text-center">
                                            <input class="shiftCheckbox" type="checkbox" name="selected" value="{{ group.id }}"/>
                                        </td>
                                        <td class="text-center">{{ group.name }}</td>
                                        <td class="text-center">
                                            <a href="">{{ group.id | members_count }}</a>
                                        </td>
                                        <td class="text-center">{{ group.comment }}</td>
                                        <td class="text-center">
                                            <a href="{% url 'juser:user_group_edit'%}?id={{ group.id }}" class="btn btn-xs btn-info">编辑</a>
                                            <a value="{% url 'juser:user_group_del' %}?id={{ group.id }}" class="btn btn-xs btn-danger del">删除</a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>

                        <div class="row">
                            <div class="col-sm-6">
                                <div class="dataTables_info" role="status" aria-live="polite">
                                    Showing {{ user_groups.start_index }} to {{ user_group.end_index }} of {{ p.count }} entries
                                </div>
                            </div>
                            {% include 'paginator.html' %}
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

{% block sel_head_css_js %}
    {% load staticfiles %}
    <script src="{% static 'js/jquery.shiftcheckbox.js' %}"></script>
{% endblock %}

{% block self_footer_js %}
    <script>
        $(document).ready(function(){
            $(".del").click(function(){
                var row = $(this).closest("tr");
                if(confirm("确定删除")){
                    $.get(
                        $(this).attr('value'),
                            {},
                            function(data){
                                row.remove();
                                alert(data);
                            }
                    )
                }
            });

            $("#del_btn").click(function(){
                var check_array = [];
                if (confirm("确定删除")){
                    $(".gradeX input:checked").each(function(){
                        check_array.push($(this).attr('value'))
                    });
                    $.get(
                            "{% url 'juser:user_group_del' %}",
                            {id:check_array.join(',')},
                            function(result){
                                alert(result);
                                $('.gradeX input:checked').closest('tr').remove();
                            }

                    );
                };
            });

            $("tbody tr").shiftcheckbox({
                checkboxSelector:'input:checkbox',
                selectAll:$('#select_all'),
                ignoreClick:'a'
            });

            $(".shiftCheckbox").shiftcheckbox();

        });

    </script>
{% endblock %}

src/templates/juser/user_list.html
{% extends 'base.html' %}
{% load mytags %}
{% block content %}
{% include 'nav_cat_bar.html' %}

    <div class="wrapper wrapper-content animated fadeinright">
        <div class="row">
            <div class="col-sm-10">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>查看用户组</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>

                    <div class="ibox-content">
                        <div class="">
                            <a href="{% url 'juser:user_add' %}" class="btn btn-primary btn-sm">添加用户</a>
                            <a id="del_btn" class="btn btn-sm btn-danger">删除所选</a>
                            <form id="search_form" method="get" action="" class="pull-right mail-search">{% csrf_token %}
                                <div class="input-group">
                                    <input type="text" class="form-control input-sm" name="search" placeholder="Search" />
                                    <div class="input-group-btn">
                                        <button id="search_btn" type="submit" class="btn btn-sm btn-primary">
                                            -搜索-
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>

                        <table class="table table-striped table-bordered table-hover" id="editable" >
                            <thead>
                                <tr>
                                    <th class="text-center">
                                        <input type="checkbox" id="select_all" name="select_all"/>
                                    </th>
                                    <th class="text-center">用户名</th>
                                    <th class="text-center">姓名</th>
                                    <th class="text-center">小组</th>
                                    <th class="text-center">权限</th>
                                    <th class="text-center">主机数量</th>
                                    <th class="text-center">激活</th>
                                    <th class="text-center">下载密匙</th>
                                    <th class="text-center">操作</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for user in users.object_list  %}
                                    <tr class="gradeX">
                                        <td class="text-center">
                                            <input class="shiftCheckbox" type="checkbox" name="selected" value="{{ user.id }}"/>
                                        </td>
                                        <td class="text-center"><a href="#">{{ user.name }}</a></td>
                                        <td class="text-center">{{ user.username }}</td>
                                        <td class="text-center" title="{% for user_group in user.group.all %}{{ user_group.name }}{% endfor %}">{{ user.group.all | groups2str }}</td>
                                        <td class="text-center">{{ user.id | get_role }}</td>
                                        <td class="text-center">{{ user.id | get_perm_asset_num}}</td>
                                        <td class="text-center">{{ user.is_active | bool2str}}</td>
                                        <td class="text-center">
                                            {% if user.username|key_exists %}
                                                <a href="{% url 'juser:key_down' %}?uuid={{ user.uuid }}">下载</a>
                                            {% else %}
                                                <a href="#" onclick="genSSH('{{ user.username }}', '{% url 'juser:key_gen' %}?uuid={{ user.uuid }}')">No Key,Gen one?</a>

                                            {% endif %}

                                        </td>
                                        <td class="text-center">
                                            <a href="{% url 'juser:user_edit' %}?id={{ user.id }}" class="btn btn-xs btn-info">编辑</a>
                                            <a href="{{ user.uuid }}" class="btn btn-xs btn-warning del">Email</a>
                                            <a href="{% url 'juser:user_del' %}?id={{ user.id }}" class="btn btn-xs btn-danger del">删除</a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>

                        <div class="row">
                            <div class="col-sm-6">
                                <div class="dataTables_info" role="status" aria-live="polite">
                                    Showing {{ user_groups.start_index }} to {{ user_group.end_index }} of {{ p.count }} entries
                                </div>
                            </div>
                            {% include 'paginator.html' %}
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

{% block sel_head_css_js %}
    {% load staticfiles %}
    <script src="{% static 'js/jquery.shiftcheckbox.js' %}"></script>
{% endblock %}

{% block self_footer_js %}
    <script>
        $(document).ready(function(){
            $(".del").click(function(){
                var row = $(this).closest("tr");
                if(confirm("确定删除")){
                    $.get(
                        $(this).attr('value'),
                            {},
                            function(data){
                                row.remove();
                                alert(data);
                            }
                    )
                }
            });

            $("#del_btn").click(function(){
                var check_array = [];
                if (confirm("确定删除")){
                    $(".gradeX input:checked").each(function(){
                        console.log($(this).attr('value'))
                        check_array.push($(this).attr('value'))
                    });
                    $.post(
                            "{% url 'juser:user_del' %}",
                            {id:check_array.join(',')},
                            function(result){
                                alert(result);
                                $('.gradeX input:checked').closest('tr').remove();
                            }

                    );
                };
            });

            $("tbody tr").shiftcheckbox({
                checkboxSelector:'input:checkbox',
                selectAll:$('#select_all'),
                ignoreClick:'a'
            });

            $(".shiftCheckbox").shiftcheckbox();

        });

    function genSSH(username, url) {
        if(confirm('Are you sure you want to gen a ssh key for user ' + username)){
           $.get(url, function(data){
                alert(data);
               location.reload();
            });

        }
    }
        // using jQuery
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');

    function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
    });

    </script>
{% endblock %}